AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    # Referencing variables inside serverless.yml file
    TableName: AuctionsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    # Things that must be in each item of the table + type
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
